create schema airport;

SET search_path = airport, public;

create table Air_company(
  AIR_COMPANY_ID INT PRIMARY KEY ,
  AIR_COMPANY_NM VARCHAR(50) NOT NULL,
  PLANE_ID INT NOT NULL REFERENCES Plane(PLANE_ID)
);

drop table Air_company;

create table Staff(
  STAFF_ID INT PRIMARY KEY ,
  AIR_COMPANY_ID INT NOT NULL REFERENCES Air_company(AIR_COMPANY_ID),
  POSITION_TITLE VARCHAR(50) NOT NULL,
  FIRST_NAME VARCHAR(30) NOT NULL,
  SECOND_NAME VARCHAR(30) NOT NULL,
  PATRONIMIC VARCHAR(30),
  FLIGHT_HOURS_NUM NUMERIC DEFAULT 0.0 CHECK (FLIGHT_HOURS_NUM>=0)
);

drop table Staff;

create table Plane(
  PLANE_ID INT PRIMARY KEY,
  PLANE_MODEL INT NOT NULL REFERENCES Plane_Model(PLANE_MODEL),
  AIR_COMPANY_ID INT NOT NULL
);

drop table Plane;

create table Plane_Model(
  PLANE_MODEL INT PRIMARY KEY,
  PASSENGERS_NUM INT NOT NULL,
  CRUISING_SPEED NUMERIC NOT NULL,
  MAX_SPEED NUMERIC NOT NULL,
  FLIGHT_RANGE NUMERIC NOT NULL,
  MAX_HEIGHT NUMERIC NOT NULL,
  RELEASE_YEAR DATE NOT NULL
);

drop table Plane_Model;

create table Flight(
  FLIGHT_NO INT PRIMARY KEY,
  PLANE_ID INT NOT NULL REFERENCES Plane(PLANE_ID),
  AIR_COMPANY_ID INT REFERENCES Air_company(AIR_COMPANY_ID),
  DEPARTURE_DTTM TIMESTAMP(0),
  ARRIVAL_DTTM TIMESTAMP(0),
  FLIGHT_DURATION NUMERIC,
  CITY_DEPARTURE_NM VARCHAR(50),
  AIRPORT_DEPARTURE_NM VARCHAR(50),
  CITY_OF_DESTINATION_NM VARCHAR(50),
  AIRPORT_DESTINATION_NM VARCHAR(50)
);

drop table Flight;

create table Maintenance(
  FLIGHT_NO INT,
  PLANE_ID INT NOT NULL REFERENCES Plane(PLANE_ID),
  MAINTENANCE_DTTM DATE,
  FIRST_NAME_RESPONSIBLE VARCHAR(30) NOT NULL,
  SECOND_NAME_RESPONSIBLE VARCHAR(30) NOT NULL,
  RESULTS VARCHAR(50)
);

drop table Maintenance;

create table Control_room(
  FLIGHT_NO INT PRIMARY KEY REFERENCES Flight(FLIGHT_NO),
  FIRST_NAME_DISPATCHER VARCHAR(30) NOT NULL,
  SECOND_NAME_DISPATCHER VARCHAR(30) NOT NULL,
  RUNWAY_NO INT NOT NULL
);

drop table Control_room;

create table Ticket(
  TICKET_NO INT PRIMARY KEY,
  AIR_COMPANY_ID INT NOT NULL REFERENCES Air_company(AIR_COMPANY_ID),
  FLIGHT_NO INT REFERENCES Flight(FLIGHT_NO),
  PASSPORT_NO INT REFERENCES Passenger(PASSPORT_NO),
  TICKET_TYPE VARCHAR(30) NOT NULL,
  TICKET_PRICE REAL NOT NULL
);

drop table Ticket;

create table Boarding_pass(
  BOARDING_PASS_NO INT PRIMARY KEY,
  FLIGHT_NO INT NOT NULL REFERENCES Flight(FLIGHT_NO),
  PLACE_NO INT NOT NULL,
  GATE_NO INT NOT NULL,
  BOARDING_TM TIME NOT NULL
);

drop table Boarding_pass;

create table Luggage(
  BOARDING_PASS_NO INT PRIMARY KEY REFERENCES Boarding_pass(BOARDING_PASS_NO),
  LUGGAGE_WEIGHT NUMERIC DEFAULT 0.0 CHECK (LUGGAGE_WEIGHT>=0)
);

drop table Luggage;

create table Passenger(
  PASSPORT_NO INT PRIMARY KEY,
  BOARDING_PASS_NO INT REFERENCES Boarding_pass(BOARDING_PASS_NO),
  FIRST_NAME VARCHAR(30),
  SECOND_NAME VARCHAR(30),
  PATRONIMIC VARCHAR(30),
  PHONE_NO INT
);

drop table Passenger;
