create schema airport;

SET search_path = airport, public;

create table Air_company(
  AIR_COMPANY_ID INT PRIMARY KEY ,
  AIR_COMPANY_NM VARCHAR(50) NOT NULL
);

create table Staff(
  STAFF_ID INT PRIMARY KEY ,
  AIR_COMPANY_ID INT NOT NULL REFERENCES Air_company(AIR_COMPANY_ID),
  POSITION_TITLE VARCHAR(50) NOT NULL,
  FIRST_NAME VARCHAR(30) NOT NULL,
  SECOND_NAME VARCHAR(30) NOT NULL,
  FLIGHT_HOURS_NUM NUMERIC DEFAULT 0.0 CHECK (FLIGHT_HOURS_NUM>=0)
);

create table Plane(
  PLANE_ID INT PRIMARY KEY,
  PLANE_MODEL VARCHAR(50) NOT NULL REFERENCES Plane_Model(PLANE_MODEL),
  AIR_COMPANY_ID INT NOT NULL REFERENCES Air_company(AIR_COMPANY_ID)
);

create table Plane_Model(
  PLANE_MODEL VARCHAR(50) PRIMARY KEY,
  PASSENGERS_NUM INT NOT NULL,
  CRUISING_SPEED NUMERIC NOT NULL,
  MAX_SPEED NUMERIC NOT NULL,
  FLIGHT_RANGE NUMERIC NOT NULL,
  MAX_HEIGHT NUMERIC NOT NULL
);

create table Flight(
  FLIGHT_NO INT PRIMARY KEY,
  PLANE_ID INT NOT NULL REFERENCES Plane(PLANE_ID),
  DEPARTURE_DTTM TIMESTAMP(0),
  ARRIVAL_DTTM TIMESTAMP(0),
  CITY_DEPARTURE_NM VARCHAR(50),
  AIRPORT_DEPARTURE_NM VARCHAR(50),
  CITY_DESTINATION_NM VARCHAR(50),
  AIRPORT_DESTINATION_NM VARCHAR(50)
);

create table Maintenance(
  MAINTENANCE_ID INT,
  PLANE_ID INT NOT NULL REFERENCES Plane(PLANE_ID),
  MAINTENANCE_DTTM DATE,
  FIRST_NAME_RESPONSIBLE VARCHAR(30) NOT NULL,
  SECOND_NAME_RESPONSIBLE VARCHAR(30) NOT NULL,
  RESULTS VARCHAR(50) CHECK (RESULTS IN ('OK', 'FAIL'))
);

create table Control_room(
  FLIGHT_NO INT PRIMARY KEY REFERENCES Flight(FLIGHT_NO),
  FIRST_NAME_DISPATCHER VARCHAR(30) NOT NULL,
  SECOND_NAME_DISPATCHER VARCHAR(30) NOT NULL
);

create table Ticket(
  TICKET_NO INT PRIMARY KEY,
  FLIGHT_NO INT REFERENCES Flight(FLIGHT_NO),
  TICKET_TYPE VARCHAR(30) NOT NULL CHECK (TICKET_TYPE IN ('ECONOMIC', 'PREMIUM')),
  TICKET_PRICE REAL NOT NULL
);

create table Boarding_pass(
  BOARDING_PASS_NO INT PRIMARY KEY,
  PLACE_NO INT NOT NULL,
  GATE_NO INT NOT NULL,
  BOARDING_TM TIME NOT NULL
);

create table Luggage(
  LUGGAGE_ID INT PRIMARY KEY,
  BOARDING_PASS_NO INT NOT NULL REFERENCES Passenger(BOARDING_PASS_NO) REFERENCES Boarding_pass(BOARDING_PASS_NO),
  LUGGAGE_WEIGHT NUMERIC DEFAULT 0.0 CHECK (LUGGAGE_WEIGHT>=0)
);

create table Passenger(
  BOARDING_PASS_NO INT REFERENCES Boarding_pass(BOARDING_PASS_NO) PRIMARY KEY,
  TICKET_NO INT REFERENCES Ticket(TICKET_NO) NOT NULL,
  PASSPORT_NO DECIMAL,
  FIRST_NAME VARCHAR(30),
  SECOND_NAME VARCHAR(30),
  PHONE_NO VARCHAR(30)
);
